### PR TITLE
adding some mods

### PR DESCRIPTION
**Pull request by hallowfiend**
one very minor hotfix, 2 pakfiles with the works and stuff

### CODE REVIEW

**Comment by apocalyptech** [comment]
Hello!

Before merging this in, could you update `youreinvited.bl3hotfix` so that the two `@license` tags are near the top of the file?  Looks like they ended up down at the bottom by accident.  :)

Cheers!

**Comment by apocalyptech** [comment]
Oh, also FYI, it looks like the uploads of the pakfiles in `tboyflynt` and `tboyvaughn` might have screwed up; those files are basically empty.  The one in `elpis_mayaifier` looks fine, though...

**Comment by hallowfiend** [comment]
both issues should be fixed now, ty for the heads up

**Comment by apocalyptech** [comment]
Heya, sorry for the delay!  Merged in now, cheers!

**Pull request merged**
