### PR TITLE
Create Operative_Com_Combo.bl3hotfix

### PR DESCRIPTION
**Pull request by PHM2D**

### CODE REVIEW

**Comment by apocalyptech** [comment]
Heya!  Have you verified that you actually need *Early* level hotfixes for this one?  I suspect that regular ol' non-Early level hotfixes would suffice.  I've been trying to keep use of Early down as much as possible.  I don't suppose you'd be willing to check and find out?  Thx!

**Comment by PHM2D** [comment]
Hey  Apocalyptech,

Unfortunately Early is necessary. Hotfix won't load without Early!

**Comment by PHM2D** [comment]
However, SparkLevelPatchEntry works fine too.

**Comment by apocalyptech** [comment]
Ah yeah, it's specifically leaving out the `Early` bit that I was hoping to confirm.  There's definitely stuff which requires `Level` hotfix, but `EarlyLevel` is practically never needed

**Comment by apocalyptech** [comment]
Awesome, thx for checking that out!  My crusade to stamp out `EarlyLevel` continues...  :D

**Comment by PHM2D** [comment]
Thank you for reminding me :) For a second I was confused about EarlyLevel and Level :D

**Pull request merged**
