### PR TITLE
Adding Mods

### PR DESCRIPTION
**Pull request by LessHandsomeJack**
Hello

### CODE REVIEW

**Comment by apocalyptech** [comment]
Hello!  Before we can merge this in, there's a couple things that need fixing:

1. Right now it's set to commit right to the top-level directory -- you'll want to create a subdirectory for your user and move the files in over there.  You can see a gif of that in action over here: https://github.com/BLCM/BLCMods/wiki/Borderlands-3-Contribution#3-create-your-user-directory-and-your-first-file
2. We're basically requiring that all mods uploaded here have a "license" specified, which basically just tells other folks what they're allowed to do with the mod.  Like, can they include your mod inside a modpack, or make some changes and upload their own version, etc.  There's a bit of info on that over here: https://github.com/BLCM/bl3mods/wiki/Contributing-to-BL3-ModCabinet#licensing - Nearly all the current mods have been licensed under [CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/), which is a pretty permissive one.  There's lots of alternatives, though, and if you just wanted to *describe* what you'd like, that'd probably be good enough too.  We just don't want there to be any ambiguity about it.

Cheers!  Let me know if you've got any questions about all that.  Feel free to hit me up on Discord if you like, too.

**Comment by apocalyptech** [comment]
Oh, and also you'll need to tweak your "categories" before they'll show up in the wiki here.  You'll want to use the strings in the "Category Name" column here: https://github.com/BLCM/bl3mods/wiki/Mod-Categories

**Comment by apocalyptech** [comment]
Hello again!  It's been three months, and we'd love to have this merged in...  We'd be happy to help with getting the files moved around properly, and putting a license on the mod file.  I'll leave this open for awhile yet -- let us know!

**Comment by LessHandsomeJack** [comment]
Hi!
Holy crap I'm so sorry I never check this email since I stopped streaming.
I read through the initial email you sent but I'm extremely new to this and
to be honest I'm very confused on what a license is and what needs to
happen with the files.
My coding/modding experience is basically limited to me crying in discord
for 9 hours while CZ47 holds my hand lol

**Comment by apocalyptech** [comment]
No worries!  It's a lot to take in.

A "license" basically just tells other people what they're allowed to do with your mod.  Like, could someone use it in a modpack, if they wanted.  Or could someone take your mod, change it to do something slightly different, and then upload *that* version, etc.  Basically the "Permissions" section at nexusmods, if you're more used to that.

As I say, so far most people have chosen this license for mods on this github: https://creativecommons.org/licenses/by-sa/4.0/ -- it basically says that other people can redistribute and modify your mod so long as they credit you, and also use the same license for their modifications.  But if you didn't like something about that, you're free to choose any other license you want.

I could certainly clean up the other formatting issues, to get this uploaded to github, but I'd want to make sure you're comfortable with a license, first.  :)

**Comment by LessHandsomeJack** [comment]
Yep that license looks good to me! Everyone is free to use my mods however
they'd like.
I would gladly accept your help with the other formatting issues. Is there
anything in particular that I need to do or look out for in future mods?

**Comment by apocalyptech** [comment]
Sure thing, I'll get that stuff cleaned up, then, and get this merged in.  Thanks for sticking with it!

As for stuff to watch out for, just basically the stuff I'd already mentioned:
1. The mod should be inside a directory of your own, rather than in the "main" directory of the repo
2. Have a license attached
3. Make sure that the categories you list use the values from the "Category Name" column at: https://github.com/BLCM/bl3mods/wiki/Mod-Categories

As I say, I'll get that stuff fixed up for you, and get this merged.  Cheers!

**Comment by apocalyptech** [comment]
Okay, should be good to go now.  Cheers!

**Pull request merged**
