### PR TITLE
Update Legendary Arms Race.bl3hotfix

### PR DESCRIPTION
**Pull request by SiKside**
I changed the drop rates now im trying to access it please

### CODE REVIEW

**Comment by apocalyptech** [comment]
Hello!  The "Pull Request" functionality you're trying to do here would update the mod on the "main" mod site, which probably isn't what you want (and we wouldn't let anyone but Poïpoï update the main mod anyway).  I'm guessing you're looking to just access the mod from your own fork?

Regardledss, closing out this PR.

**Comment by SiKside** [comment]
Yes sorry Im very new to this website. I just wanted to edit the values for my own use if possible.


Sent from Yahoo Mail for iPhone


On Monday, March 28, 2022, 4:59 PM, CJ Kucera ***@***.***> wrote:




Hello! The "Pull Request" functionality you're trying to do here would update the mod on the "main" mod site, which probably isn't what you want (and we wouldn't let anyone but Poïpoï update the main mod anyway). I'm guessing you're looking to just access the mod from your own fork?

Regardledss, closing out this PR.

**Comment by apocalyptech** [comment]
Yeah, no worries!  If you were looking to just add your version into B3HM, I expect you'd want to use this URL: https://raw.githubusercontent.com/SiKside/bl3mods/master/Po%C3%AFpo%C3%AF/Legendary%20Arms%20Race.bl3hotfix

I'm not really familiar with how people use that mod, though, so I can't really say for certain.  I'd recommend stopping by the Discord to ask about it, if you're still having problems.  :)

**Comment by SiKside** [comment]
Thank you kind sir 😁


Sent from Yahoo Mail for iPhone


On Monday, March 28, 2022, 5:04 PM, CJ Kucera ***@***.***> wrote:




Yeah, no worries! If you were looking to just add your version into B3HM, I expect you'd want to use this URL: https://raw.githubusercontent.com/SiKside/bl3mods/master/Po%C3%AFpo%C3%AF/Legendary%20Arms%20Race.bl3hotfix

I'm not really familiar with how people use that mod, though, so I can't really say for certain. I'd recommend stopping by the Discord to ask about it, if you're still having problems. :)

**Pull request closed without merging**
