### PR TITLE
Create Remove Health Gates.bl3hotfix

### PR DESCRIPTION
**Pull request by Lonemaster**
First real thing I'm doing here, let me know if anything is missing.

### CODE REVIEW

**Comment by apocalyptech** [comment]
Hello!  Looks good, though I'd encourage you to put a license on the mod so that folks know what they're allowed to do with it.  If you don't want to, that's fine, and I'll merge in the PR right away.  Otherwise, feel free to add in the licensing info and I'll merge it once you do.  Thanks!

**Comment by Lonemaster** [comment]
Hi! Sorry, but I'm not sure I understand what you mean by "licensing info"?
As you can tell, I'm entirely new to this, so if it isn't too much trouble
I'd like an explanation on the ramifications of that.

**Comment by apocalyptech** [comment]
No worries!  There's a bit of information on it here: https://github.com/BLCM/bl3mods/wiki/Contributing-to-BL3-ModCabinet

It's basically just something you can put on the mod so that other people know if they're allowed to do things like use your mod in a mod pack, or alter your mod and upload their changes, or even upload your mod elsewhere.  I've been putting mine under this pretty open creative commons license: https://creativecommons.org/licenses/by-sa/4.0/ ... but you are of course welcome to use whatever you like with it.

I think that Creative Commons licenses fit these kinds of mods pretty well.  They've got a handy webpage you can use to choose which of theirs works for you, if you wanted to do that: https://creativecommons.org/choose/ -- or you could opt to use something other than CC.

As I say, it's not *really* required to put a license on your mod, but I've been really strongly encouraging it.  A lot of the BL2/TPS mods don't have any licenses specified at all, which has led to a lot of confusion and drama in the past, so I've been attempting to avoid that w/ BL3 modding.  :)

**Comment by Lonemaster** [comment]
Sorry for the late reply; my computer decided it'd be fun to forcefully
install an update that I told it to install overnight. Regardless, I have
put the little license block on the file. If there's anything else that'd
be helpful to do, please let me know. If not, you can do the merge and
whatnot. Once again, thanks for helping me out, it's appreciated.

Am So., 14. März 2021 um 08:27 Uhr schrieb CJ Kucera <
***@***.***>:

**Comment by apocalyptech** [comment]
Sweet, thanks!  :)  Have a good one!

**Pull request merged**
