### PR TITLE
HotFix Manager

### PR DESCRIPTION
**Pull request by TrevorSTroxel**
More progress has been made for making a UI interface for easier use.
Coding is coming along. Still a lot of errors, but progress is being made.

### CODE REVIEW

**Comment by apocalyptech** [comment]
Heya!  Fun stuff!  It looks like this current PR adds a new top-level dir of "Hotfix Manager," though -- did we want to keep that stuff in your own user dir for now?  Or maybe under `python_mod_helpers` instead?  Not sure if we should put it at the top level at the moment.

**Comment by TrevorSTroxel** [comment]
Sorry about that. I did change the file name, but i forgot to change it back to what it was originally was called. i just changed for my sake so I could find it easier. If you don't mind putting it under python_mod_helpers, I would be more than happy to do so.

**Comment by TrevorSTroxel** [comment]
The "Hotfix Manager" is just the "TrevorSTroxel" file found normally on the site. again sorry for not responding sooner.

**Comment by apocalyptech** [comment]
No worries!  Not like this stuff is urgent. :)

I think it probably makes sense for this to go under the `python_mod_helpers` dir; could you move stuff in there?  You might want to rename the dir from `Hotfix Generator` to be something like `hotfixgenerator` so that it'd be properly importable -- I notice you've got an `__init__.py` in there, so having a directory name without spaces would probably be good.

Two other pretty minor points about what's in the PR currently:
1. You're checking in a file in a `.vscode` directory.  I think we should probably omit that.  If you add a line to the project's `.gitignore` which just says `.vscode`, that should get it omitted, and then folks can define their own vscode parameters without interfering
2. I see there's an empty `search_results.txt` at the root; that should probably get deleted as well.

Thanks!

**Comment by TrevorSTroxel** [comment]
Sorry for the late reply again. being a college student cant eat at all your time most days. anyway I can do that. Ill close this pull request and do a new one. Thanks for communicating this to me. im pretty excited to be working on this project

**Comment by apocalyptech** [comment]
No worries!  We've all got other stuff to do.  :)

Feel free to keep this one open if you want -- as you commit stuff to your fork, this one will just automatically update.  I don't mind having it remain open until you're good.

Cheers!

**Comment by TrevorSTroxel** [comment]
I believe now everything is in order.

**Comment by apocalyptech** [comment]
Yep, looks good, thx!

**Pull request merged**
